### ISSUE TITLE
Make trailing dot domains work

### ISSUE THREAD

**Issue by annevk** [whatwg/whatwg.org#100]
Such as https://whatwg.org./. We should probably redirect them to the version without the dot.

**Comment by foolip** [comment]
https://idea.whatwg.org./. does work, so presumably this will just work when we take over hosting of whatwg.org.

**Comment by annevk** [comment]
Ah great, so it's only the redirect issue that remains.

**Comment by domenic** [comment]
Seems like per #61 we're not pursuing this? Feel free to reopen if so.

**Comment by foolip** [comment]
It works now, but no redirects to normalize are added. (When the issue was filed it was broken.)
