### ISSUE TITLE
Add Loader to idea.whatwg.org

### ISSUE THREAD

**Issue by annevk** [whatwg/whatwg.org#114]
See https://github.com/whatwg/whatwg.org/pull/98#issuecomment-341021674 by @xfq.

**Comment by foolip** [comment]
Is loader likely to live on? Outcome of https://github.com/whatwg/loader/issues/159 isn't clear to me.

**Comment by annevk** [comment]
I don't think so, given that some involved are now looking at service workers, but it doesn't seem more or less successful than the other ideas listed.

**Comment by annevk** [comment]
This isn't worth the effort required at this point.
