### ISSUE TITLE
Change footer to recommend filing issues on whatwg/meta

### ISSUE THREAD

**Issue by domenic** [whatwg/whatwg.org#13]
Currently it reads

> Queries should be directed either to one of our mailing list or to Ian Hickson, who is acting as a spokesman for the group.

**Comment by domenic** [comment]
I guess maybe this is worth discussing though since everyone has email and not everyone has a GitHub account.

**Comment by annevk** [comment]
We should at least mention this repository in more places. Perhaps there should be some kind of contact thingy for press where we mention Ian's address and for general website issues we require GitHub.
