### ISSUE TITLE
Automate generating whatwg.org policy pages from whatwg/sg

### ISSUE THREAD

**Issue by domenic** [whatwg/whatwg.org#133]
The script in #132 is used to generate several pages on whatwg.org from Markdown documents in whatwg/sg. We should figure out a way to automate this.

Several possibilities:

1. Build process lives here in whatwg/whatwg.org's Travis job; pushes to whatwg/sg trigger a whatwg/sg Travis job which uses https://docs.travis-ci.com/user/triggering-builds to trigger the whatwg/whatwg.org Travis job.
2. The Travis job for whatwg/sg could do the build, then commit and push the generated output into whatwg/whatwg.org directly, thus indirectly triggering the whatwg/whatwg.org Travis job (which just does a deploy).
3. The Travis job for whatwg/sg pushes a small file containing a commit hash for whatwg/sg into whatwg/whatwg.org, and the whatwg/whatwg.org build process uses whatever hash is committed to build. (A variant on (1).)

I like (1) the most.

**Comment by annevk** [comment]
Reading triggering-builds it sounds like whatwg/sg needs to get a private key and associate that with Travis. That key needs to encrypt the whatwg/whatwg.org token and then the whatwg/sg build script decrypts it and uses it to trigger the whatwg/whatwg.org build.

That way we can use Travis for everything and don't need a script on a server that's triggered through a webhook. Does that sound accurate? I can work on that, but I think @domenic can probably pull it off a little quicker.

**Comment by annevk** [comment]
https://hiddentao.com/archives/2016/08/29/triggering-travis-ci-build-from-another-projects-build/ documents this though it uses Node.js when a simple curl would hopefully do.

**Comment by annevk** [comment]
Given the low volume of changes doing this manually has been fine.
