### ISSUE TITLE
convert-policy.py gets some stuff in parentheses wrong

### ISSUE THREAD

**Issue by foolip** [whatwg/whatwg.org#134]
Moved from https://github.com/whatwg/sg/issues/45, details there.

**Comment by othermaciej** [comment]
My understanding of the issue is that parens after brackets should not be treated as a link if there is an intervening space. Global replace of "] (" to "] (" as a preprocessing step should do it, I think.

**Comment by foolip** [comment]
"] (" and "] (" are the same string, typo?

**Comment by annevk** [comment]
GitHub has a tendency to remove `\`. I recommend using backticks around strings to be sure.

**Comment by domenic** [comment]
Fixed by f716ffa145598093d0567d955fde6c4fc9d3a4d1
