### ISSUE TITLE
Original HTML multipage spec links broken - needs redirect fix

### ISSUE THREAD

**Issue by tantek** [whatwg/whatwg.org#142]
Links to the original HTML multipage spec now all redirect to top of the HTML spec all-in-one-page and thus are effectively broken (trying to hunt to find what you thought you were looking for through the entire spec is not reasonable).

There are LOTS of links of the form www.whatwg.org/specs/web-apps/current-work/multipage on the web pointing to specific pages and sections (in email archives etc.) and these really should keep working.
 
Current behavior: links of the pattern
* http://www.whatwg.org/specs/web-apps/current-work/multipage/abc.html#def 
All redirect to 
* https://html.spec.whatwg.org/

Expected behavior: links of the pattern 
* http://www.whatwg.org/specs/web-apps/current-work/multipage/abc.html#def 
Redirect to:
* https://html.spec.whatwg.org/multipage/abc.html#def

Specific example:
* http://www.whatwg.org/specs/web-apps/current-work/multipage/links.html#other-link-types
Should redirect to:
* https://html.spec.whatwg.org/multipage/links.html#other-link-types

**Comment by annevk** [comment]
Thanks. I'm guessing this must have regressed as part of the move to Nginx. https://github.com/whatwg/misc-server/blob/master/debian/marquee/nginx/sites/whatwg.org.conf#L124 doesn't seem to account for multipage/ links.

@foolip?

**Comment by foolip** [comment]
The original Apache setup is in https://github.com/whatwg/whatwg.org/commit/928a87b46ed790c5ea86e2ea52056f413f0a0cd6.

I was quite conservative in the conversion and AFAICT this ought to not have worked before either. Hard to say with confidence without erecting the Apache server again though.

Anyway, I can make them work.

**Comment by annevk** [comment]
In particular `redirect 301 /specs/web-apps/current-work/ https://html.spec.whatwg.org/` suggests to me that `https://whatwg.org/specs/web-apps/current-work/x` would go to `https://html.spec.whatwg.org/x`. Currently that just redirects to `https://html.spec.whatwg.org/`.

**Comment by annevk** [comment]
Nginx seems to do some kind of catch-all approach rather than forwarding the original subpath+query.

**Comment by foolip** [comment]
Aha, you're right, that "multipage" didn't appear in the destination URL doesn't mean it didn't work.

**Comment by annevk** [comment]
We should probably also vet the other redirects just in case we turned more into catch-all where we simply wanted to forward the original subpath+query (no idea what the term for this would be).

**Comment by foolip** [comment]
I'm pretty sure the problem here is at "fall back to single-page HTML". Any return 30x line that doesn't have a `$1` or $2` in it is redirecting everything to a fixed URL. I had to make some judgements about things like that, but this one was a mistake and not deliberate.

**Comment by annevk** [comment]
Okay, I guess we do have plenty of redirect tests already so we just need to add some for this.

**Comment by foolip** [comment]
OK, so what I didn't realize was that the original "redirect 301 /specs/web-apps/current-work/ https://html.spec.whatwg.org/" was intending to preserver a trailing /multipage/. An easy fix coming up.

**Comment by foolip** [comment]
http://www.whatwg.org/specs/web-apps/current-work/multipage/links.html#other-link-types works with https://github.com/whatwg/misc-server/pull/63

**Comment by annevk** [comment]
Thanks @tantek!

**Comment by annevk** [comment]
(Note that you might have to clear cache to get this to work.)

**Comment by foolip** [comment]
Looking through whatwg.org.conf looking for other "squashing" redirects I don't see anything else that looks suspicious, so I think we're good here.

**Comment by tantek** [comment]
Works great. Thanks for the quick fix @foolip @annevk !
