### ISSUE TITLE
Consider renaming files with question marks in them in this repo

### ISSUE THREAD

**Issue by domenic** [whatwg/whatwg.org#150]
The forums.whatwg.org subdirectory contains files which have question marks in their name. Unfortunately it appears that makes Git on Windows totally unusable for this repository.

I've been working around this by using the Windows Subsystem for Linux, but that has some limitations, and e.g. I can't use my usual text editor.

It would be ideal if perhaps we could rename these files to some other filenames (e.g. use `__` instead of `?`) and then use the server config to map ?s to that other filename.

**Comment by foolip** [comment]
This would be a pretty easy fix and I actually looked at https://serverfault.com/a/674854 when setting this up without actually doing it because I thought that `&` is probably also reserved which would take a few more lines of code. Seems like it isn't though, so I'll give this a try.

**Comment by foolip** [comment]
OK, two PRs sent and confirmed to be working live briefly before being reverted. We don't have automatic deploy so when reviewed I'll have to merge them both and do some fiddling.
