### ISSUE TITLE
Deduplicate the whatwg/sg integration a bit

### ISSUE THREAD

**Issue by annevk** [whatwg/whatwg.org#173]
It seems the Python script invoked from `deploy.sh` should be able to do everything based on `policy-link-mappings.txt` (from whatwg/sg) and not need to be invoked five times.

(This should even work once the SG adds working-mode and code-of-conduct as they'll just end up overwriting the existing files, though we should at that point also update this repository to remove them here.)

**Comment by othermaciej** [comment]
I might need to update policy-link-mappings.txt a bit to make it easy to tell which documents should be converted and which are just link changes, but otherwise this should be fairly straightforward.

**Comment by annevk** [comment]
That should not be a problem as long as changes to the whatwg/sg repository do not trigger changes here.

**Comment by othermaciej** [comment]
I'll have to do it in a way that doesn't require synchronized merges. Should be doable.
