### ISSUE TITLE
Making lint checks and Bikeshed warnings fatal

### ISSUE THREAD

**Issue by annevk** [whatwg/whatwg.org#176]
Once #172 has landed we have enabled lint checking and each standard using the shared build script will output the results of those checks. They already report Bikeshed warnings.

We need to investigate those warnings for each standard and see where they need to be addressed and then address them.

Then once all standards no longer report warnings we need to make them fatal so they cannot be introduced in the future.

An alternative here is that we provide a `.travis.yml` flag so you can opt-in to strict warnings to make this transition easier, but I'd rather just go all the way.

**Comment by annevk** [comment]
* MIME Sniffing is still in a bad state here
* XMLHttpRequest has a false-positive on spelling that I'm not sure how to remove

**Comment by domenic** [comment]
What's the XHR false positive?

We could use a comment strategy like we did for en-GB.

**Comment by annevk** [comment]
It does not like my example `unicorns-are-teh-awesome.txt`.

**Comment by domenic** [comment]
The new "Informative classes" thing is creating new warnings in various standards now that domintros are properly classed as non-normative.

**Comment by domenic** [comment]
https://github.com/tabatkins/bikeshed/issues/1329 is now implemented. We should audit all existing warnings and see if we can just flip the flag and fix them as we go, or need something more complicated.

**Comment by annevk** [comment]
@plinss could you add support for --die-on to https://api.csswg.org/bikeshed/ pretty please?

**Comment by plinss** [comment]
Added

**Comment by annevk** [comment]
If you use `output=err`, would this parameter affect the output? I've intentionally not passed it to that particular Bikeshed call in my PR, but it would simplify things a bit if it didn't matter and I could pass it there.

**Comment by plinss** [comment]
This parameter is orthogonal to output. `output=err` gives you the stdout and stderr output of bikeshed (with the generated output going to a temp file). The `--die-on` only changes what bikeshed considers to be a fatal error, which IIRC only affects the generated output (though it may stop on the first fatal error?).

**Comment by tabatkins** [comment]
It tries to exit with a non-zero exit code, yeah.
