### ISSUE TITLE
Inconsistent <title>s

### ISSUE THREAD

**Issue by annevk** [whatwg/whatwg.org#178]
The titles from whatwg/sg currently end up as "WHATWG Subject". Should we align with that locally (we have "Web Hypertext Application Technology Working Group Subject") or would it be better to use something like "Subject — WHATWG"?

I have a slight preference for the latter as then favicon plus "Subject" still gives you a bit of a clue when the tabs get small whereas putting WHATWG first will make them all look the same.

**Comment by domenic** [comment]
I was planning on redoing titles across the site as part of #154. I was initially thinking "WHATWG Subject" but I do think "Subject — WHATWG" sounds a bit better.

**Comment by domenic** [comment]
However note than in all browsers but Firefox our favicon is useless, so we do lose context in that way.

**Comment by snuggs** [comment]
@annevk [Poe's Law](https://en.wikipedia.org/wiki/Poe%27s_law)? 😂
