### ISSUE TITLE
Home page sometimes lacks margins on the side

### ISSUE THREAD

**Issue by annevk** [whatwg/whatwg.org#180]
There is a point where when you make the browser small enough the home page no longer has side margins. This looks rather ugly and you can end up triggering this look fairly easily.

Also, instead of switching from 1 row of 4 links to 4 rows of 1 link for "self-explanatory-links", perhaps we can do 2 rows of 2 links on a small screen?

**Comment by domenic** [comment]
As part of #154 (see https://whatwgorg-fagezotxgs.now.sh/) I ended up making them just smaller, instead of one row of four links. Although it doesn't scale down infinitely; at some point it just starts scrolling.

Can work on the margins as part of #154 too.

**Comment by snuggs** [comment]
@annevk a picture is worth a thousand words. Of course can attempt manually but your eyes may see the pain more than mine.

Thanks in advance for the nit 🙏

**Comment by snuggs** [comment]
crap. Github and it's lack to update comments without refreshing. Had this tab up all day.

disregard previous comment.
