### ISSUE TITLE
robots.txt and Internet Archive

### ISSUE THREAD

**Issue by wakaba** [whatwg/whatwg.org#19]
Old snapshots of WHATWG specs in the Internet Archive are now blocked by robots.txt.  For example, https://web.archive.org/web/20040605213911/http://www.whatwg.org/specs/web-apps/current-work/ says:

> Page cannot be displayed due to robots.txt.
> See www.whatwg.org robots.txt page.

Could the robots.txt restrictions be relaxed?

**Comment by foolip** [comment]
Yeah, that's bad. https://github.com/whatwg/whatwg.org/blob/master/src/robots.txt is the file, do you know the syntax for explicitly allowing web.archive.org?

**Comment by annevk** [comment]
Found some syntax and created a PR.

**Comment by foolip** [comment]
https://whatwg.org/robots.txt is now updated but https://web.archive.org/web/20040605213911/http://www.whatwg.org/specs/web-apps/current-work/ is still gone. Maybe it'll be back in a bit, or perhaps it's gone forever?
