### ISSUE TITLE
Delete status-2008-12?

### ISSUE THREAD

**Issue by domenic** [whatwg/whatwg.org#2]
Seems confusing to keep

**Comment by annevk** [comment]
I think we should keep all resources that might be linked. We can add a disclaimer at the top of them indicating they're no longer current, but I don't see good reason to remove them.

Alternatively we could do what Ian suggested which is to move them to some kind of archiving site and add redirects, but that just seems like more work.

**Comment by foolip** [comment]
https://web.archive.org/web/20081221111158/http://www.whatwg.org/status-2008-12 already existed so we could use that, but it would be a bit of work to try to do this for everything.
