### ISSUE TITLE
Overlapping text on some pages

### ISSUE THREAD

**Issue by xfq** [whatwg/whatwg.org#21]
The `h1` element on some pages (such as spec.whatwg.org, and the 404 page) looks weird:

<img width="759" alt="screen shot 2017-02-15 at 10 05 33 pm" src="https://cloud.githubusercontent.com/assets/2863444/22977952/b494fc8a-f3cb-11e6-8f46-02f87c32896a.png">

"The" and "Web" overlaps. It might be caused by this rule: https://github.com/whatwg/whatwg.org/blob/56109a1a0575b81d7c12bc5273677249856e31ef/src/style/tabbed-pages#L20 (the `margin` declaration)

**Comment by domenic** [comment]
Last I checked this is an intentional stylistic choice, but I guess a PR making it less "weird" would be reasonable.
