### ISSUE TITLE
Service worker network fallback is not working

### ISSUE THREAD

**Issue by domenic** [whatwg/whatwg.org#211]
I actually debugged through [the standard service worker](https://github.com/whatwg/whatwg.org/blob/c3cee440c87c51e37f26fff5696becb97d113944/resources.whatwg.org/standard-service-worker.js) today and found out their our refresh-the-cache logic was not working at all. In particular, it appears that the responses that reach https://github.com/whatwg/whatwg.org/blob/c3cee440c87c51e37f26fff5696becb97d113944/resources.whatwg.org/standard-service-worker.js#L69 are often (always?) opaque, and so res.ok is false.

I noticed that https://jakearchibald.com/2014/offline-cookbook/#stale-while-revalidate does not have this check.

The opaqueness was somewhat unexpected, since all resources are delivered with `ACAO: *`. They are cross-origin though (resources.whatwg.org resources, like stylesheets, are not the same origin as the standards).

I see a few options:

- Add `mode: "cors"` to our refresh-the-cache fetches, under the assumption that we'll only be caching whatwg.org resources, which have ACAO: *. I imagine this will make the resources non-opaque.
- Remove the `res.ok` check and cache unconditionaly.

Any other ideas? Which sounds better? @jakearchibald @annevk.

Regardless, it may be worth reconsidering https://github.com/whatwg/whatwg.org/blob/c3cee440c87c51e37f26fff5696becb97d113944/resources.whatwg.org/standard-service-worker.js#L49, as it made diagnosing this quite tricky.

**Comment by annevk** [comment]
I don't understand how they're opaque. When you use `importScripts()` the imported script executes with the authority of the importer, which should be same origin with whatever is being requested?

**Comment by jakearchibald** [comment]
I'll dig into this on Monday

**Comment by domenic** [comment]
No, the importer is e.g. dom.spec.whatwg.org/service-worker.js, whereas the resource is resources.whatwg.org/spec.css or similar.

**Comment by jakearchibald** [comment]
Looking through the code:

`needsToBeFresh` should probably just check `request.mode === 'navigate'` I think. This means non-root navigations will also be considered fresh, which makes sense for specs hosted on github pages. Although maybe you'd provide an array of extras that should also be fresh.

For the `res.ok` check, you could do:

```js
if (res.type !== 'opaque' && !res.ok) // throw or return
```

So opaque resources are just cached as-is. But opaque stuff is bad for the 5xx reasons @annevk mentioned, and also because they take up a lot of quota due to bucketing for security reasons. You could add `crossorigin` to the script & CSS resources to reduce this, but that won't work for images the CSS loads (afaik), but maybe there aren't may of those?

**Comment by domenic** [comment]
Thanks, I'll role these changes into https://github.com/whatwg/whatwg.org/pull/202. What do you think of only refreshing the cache with `mode: "cors"`, i.e. modifying https://github.com/whatwg/whatwg.org/blob/c3cee440c87c51e37f26fff5696becb97d113944/resources.whatwg.org/standard-service-worker.js#L47 to add that to the request?

**Comment by domenic** [comment]
Related reading: https://cloudfour.com/thinks/when-7-kb-equals-7-mb/

**Comment by domenic** [comment]
Maybe the right solution is to just add crossorigin="" attributes everywhere. Did that in https://github.com/tabatkins/bikeshed/pull/1312.

Or, it could be to modify all outgoing requests to add mode: "cors", which should be pretty similar (except on first run without a service worker installed)?
