### ISSUE TITLE
Angle brackets need escaping in https://whatwg.org/irc

### ISSUE THREAD

**Issue by deanedridge** [whatwg/whatwg.org#212]
Regarding the WHATWG IRC info web page:
<a href="https://whatwg.org/irc">https://whatwg.org/irc</a>
<a href="https://github.com/whatwg/whatwg.org/blob/master/whatwg.org/irc">https://github.com/whatwg/whatwg.org/blob/master/whatwg.org/irc</a>

Viewing source on the whatwg.org site at the moment shows:
"<pre>
   botie, inform &lt;nick&gt; [that|to|about] &amp;lt;message&amp;gt;
</pre>"

But should be:
"<pre>
   botie, inform &amp;lt;nick&amp;gt; [that|to|about] &amp;lt;message&amp;gt;
</pre>"

**Comment by domenic** [comment]
Great catch! Would you be up for making a pull request?
