### ISSUE TITLE
Redo "Join" on the home page

### ISSUE THREAD

**Issue by annevk** [whatwg/whatwg.org#23]
Some thoughts:

* We should do away with redirecting to the mailing lists, in particular the help list is effectively replaceable with a link to stackoverflow.com. I kinda feel we should maybe give up on it altogether, but maybe that's still too soon.
* If we do that, we need a place where new people can go. So maybe a page that lists what you can do as we already have on the wiki (but more up-to-date and with less information). Review standards, work on tests, write standards, go through old issues...
* Ideally once we have "working mode" we can also link to it somehow. New tabbed page?

**Comment by domenic** [comment]
Getting rid of/replacing the mailing lists page is a good idea.

A good landing page for new people is also a good idea. It can include the link to good first bugs as well.

Working mode as a new tabbed page makes sense to me. Also probably the revised FAQ as such a page.

**Comment by annevk** [comment]
If we end up merging Join and Volunteer, what else should we link to?

Rename "News" to "Blog" maybe?

**Comment by annevk** [comment]
This is now #89. If anyone else wants to rename "News" let me know and I'll get that fixed.
