### ISSUE TITLE
Preview feature for whatwg.org PRs

### ISSUE THREAD

**Issue by annevk** [whatwg/whatwg.org#26]
Either we start using mod_rewrite to keep URLs the same but have extensions for local viewing or we need some kind of preview setup to make things easier to review.

**Comment by foolip** [comment]
This was closed because we merged in the history of https://github.com/whatwg/resources.whatwg.org, reopening.

**Comment by annevk** [comment]
Before/after screenshots have worked well thus far. Not really convinced we need a lot of infrastructure here given the volume of changes.
