### ISSUE TITLE
html.spec.whatwg.org website down

### ISSUE THREAD

**Issue by jason-gu** [whatwg/whatwg.org#261]
Looks like the website for HTML spec is down, error => "This site can’t be reached"

**Comment by domenic** [comment]
Seems to be fine at the moment: https://downforeveryoneorjustme.com/html.spec.whatwg.org/

Server logs show no 5xx errors in the last 24 hours, although I suppose there could have been a problem that caused the server to not even receive the response.

Closing, as this seems to be working fine, but let us know if you experience this in the future!
