### ISSUE TITLE
convert-policy.py and Python 3

### ISSUE THREAD

**Issue by annevk** [whatwg/whatwg.org#264]
I'm guessing we need to update this or will Travis et al support Python 2.7 for the foreseeable future?

**Comment by domenic** [comment]
Various things have gotten more aggressive about removing Python 3 support. Also, [our builds have started failing with weird encoding errors](https://travis-ci.org/whatwg/whatwg.org/builds/659206562#L206), even on Python 2. So, we should probably do something here sooner rather than later.
