### ISSUE TITLE
Improve styles for tracking vector image

### ISSUE THREAD

**Issue by annevk** [whatwg/whatwg.org#281]
As shown in https://usercontent.irccloud-cdn.com/file/EplnfaoQ/Screenshot_20200114-073026.png by @tabatkins we need to do something better for smaller screens. Rendering it inline seems reasonable?

**Comment by domenic** [comment]
This feels like the use case for `float: right`, no?

**Comment by tabatkins** [comment]
Yeah, that's what I'm immediately leaning towards too.
