### ISSUE TITLE
Too many files for deploy to list them all

### ISSUE THREAD

**Issue by foolip** [whatwg/whatwg.org#287]
https://github.com/whatwg/whatwg.org/pull/285 added 103k files which broke deploy on Travis due to exeeding the maximum log length. We have in total 108k files in the repo now.

https://github.com/whatwg/whatwg.org/pull/286 didn't work, and to get things working ASAP I'm going to suggest not logging the files at all.

Filing this issue to keep track of the problem.

**Comment by annevk** [comment]
My suggestion is that we use --log-file=FILE and then scp that file (if it doesn't get synced) so it can be read over HTTP if someone is interested.

**Comment by annevk** [comment]
See also #290.

**Comment by foolip** [comment]
Thanks for finishing what I broke, @annevk!
