### ISSUE TITLE
convert-policy.py and Markdown

### ISSUE THREAD

**Issue by annevk** [whatwg/whatwg.org#291]
* The only affect of `from mdx_partial_gfm import PartialGithubFlavoredMarkdownExtension` appears to be the auto-linking of the email address in the Code of Conduct. We could consider replacing it with something simpler that handles email addresses.
* Adopting `commonmark` would require some restructuring of the code as it doesn't like some of the pre-processing we do. It ends up wrapping our headings with paragraphs and also encodes a bunch of " as `&quot;`.

It's not clear that making either is worth it.

**Comment by domenic** [comment]
I think Commonmark is worth a lot just in being the same as GitHub and helping the Markdown ecosystem converge toward a single spec.

**Comment by annevk** [comment]
Could it be that the Python `commonmark` package is wrong? https://spec.commonmark.org/ behaves very similar to the `markdown` package we are using, especially for input such as
```
<h3>...</h3>
test
```
or
```
<h3>...</h3>

test
```
whereas if I try that locally with the `commonmark` package the `<h3>` ends up wrapped in a `<p>`.

**Comment by domenic** [comment]
That could be possible, if distressing :(. Although as I noted in https://github.com/whatwg/sg/pull/92#issuecomment-596056668 I'm unsure why our input contains `<h3>`s anyway, instead of `###`.

**Comment by annevk** [comment]
That's what convert-policy does. We could possibly change it to do post-HTML-conversion changes. That would also fix #145. But I don't think I've really seen where commonmark and markdown give different results yet. Other than that commonmark didn't do email address auto-linking. (Perhaps it needs to be wrapped inside angle brackets.)
