### ISSUE TITLE
Update FAQ for AppCache removal

### ISSUE THREAD

**Issue by TimothyGu** [whatwg/whatwg.org#345]
The [FAQ](https://whatwg.org/faq) still says:

> Two recent removals from the platform include the [`applet`](https://github.com/whatwg/html/pull/1399) and [`keygen`](https://github.com/whatwg/html/pull/2221) elements. An in-progress removal, which may or may not be successful, is the [AppCache](https://html.spec.whatwg.org/multipage/offline.html#offline) feature.

with the link to AppCache dead due to https://github.com/whatwg/html/pull/6153.

If the AppCache removal may be considered successful, then we should instead say

> A recent removal from the platform is the [AppCache](https://github.com/whatwg/html/pull/6153) feature.

**Comment by annevk** [comment]
Thanks for spotting and reporting that! I created #346.
