### ISSUE TITLE
Rename src/ to whatwg.org/

### ISSUE THREAD

**Issue by annevk** [whatwg/whatwg.org#42]
Once whatwg.org moves to the same server idea.whatwg.org is on we could rename src/ to whatwg.org and we could put spec.whatwg.org in its own directory rather than the current setup.

We could then also put some of the redirect and .htaccess logic here for all of the server. Though that depends a bit on how we want to organize all that and where it's best to put it.

**Comment by domenic** [comment]
Oh, this makes a lot of sense.

Maybe more future-proof would be src/whatwg.org and src/spec.whatwg.org since we can then reserve the top-level for stuff that never gets deployed anywhere.

**Comment by foolip** [comment]
I think that as long as we have no other directories named *whatwg.org, putting the directories in the root wouldn't make anything harder. But whoever does the work gets to decide :)
