### ISSUE TITLE
Redirect various things to resources.whatwg.org

### ISSUE THREAD

**Issue by domenic** [whatwg/whatwg.org#6]
- style/specification
- images/logo*

Would be good to find out if anything is using them and update the links too

**Comment by annevk** [comment]
There is a lot of references to these from the older specifications, especially HTML multipage.

**Comment by annevk** [comment]
This also doesn't seem worth the effort. In particular the risk of breaking the appearance of things we no longer maintain doesn't seem worth it. Just don't link to the old resources.
