### ISSUE TITLE
Fetching deploy.sh keeps failing

### ISSUE THREAD

**Issue by annevk** [whatwg/whatwg.org#65]
This is for Fetch's master:
```
Setting environment variables from .travis.yml
$ export ENCRYPTION_LABEL="e149beb9c312"
$ export DEPLOY_USER="annevankesteren"

$ bash -c 'echo $BASH_VERSION'
4.3.11(1)-release

0.43s$ curl --remote-name --fail https://resources.whatwg.org/build/deploy.sh && bash ./deploy.sh
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  5503  100  5503    0     0  21895      0 --:--:-- --:--:-- --:--:-- 21924
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100    87  100    87    0     0    574      0 --:--:-- --:--:-- --:--:--   576

The command "curl --remote-name --fail https://resources.whatwg.org/build/deploy.sh && bash ./deploy.sh" exited with 1.

Done. Your build exited with 1.
```
Fetch it from `https://raw.githubusercontent.com/whatwg/whatwg.org/master/resources.whatwg.org/build/deploy.sh` instead? And if we go down that path, no longer host it on `resources.whatwg.org` as we fetch it from GitHub anyway?

cc @domenic @foolip

**Comment by annevk** [comment]
https://travis-ci.org/whatwg/fetch/builds/269117879

**Comment by foolip** [comment]
Is this a flaky failure? I can currently access https://resources.whatwg.org/build/deploy.sh just fine.

**Comment by foolip** [comment]
I've restarted the build to see.

**Comment by annevk** [comment]
FWIW, I already had restarted it four times while being able to access that resource just fine myself. It's rather unclear what's going on.

**Comment by foolip** [comment]
Might be because of the new deploy method for resources.whatwg.org, perhaps?

**Comment by foolip** [comment]
But I can't exactly how that could be, since the resource is there.

**Comment by annevk** [comment]
Nah, this happened before this switch as well.

**Comment by foolip** [comment]
https://github.com/whatwg/fetch/pull/587 didn't give much of a clue :/

**Comment by foolip** [comment]
Has this been happening for all repos?

**Comment by annevk** [comment]
Yeah, they just haven't been updated much recently so I haven't hit it a lot.

**Comment by annevk** [comment]
Saw it on whatwg/dom too and whatwg/encoding. https://travis-ci.org/whatwg/encoding/builds/265476353 is slightly different though. Maybe it's @sideshowbarker's server that is unresponsive and the problem is with fetching that happens in the deploy.sh script?

**Comment by domenic** [comment]
To me the first failing build looks like the deploy.sh fetch succeeds but the first curl inside deploy.sh fails. That would be this one:

```
SERVICE_WORKER_SHA=$(curl https://api.github.com/repos/whatwg/resources.whatwg.org/contents/standard-service-worker.js \
                     -H "Accept: application/vnd.github.v3+json" \
                     | grep -Po '(?<="sha": ")[^"]*') # Hacky JSON parsing but works for SHAs
```

That gives a 404 since the repo move, so that's probably the issue here.

**Comment by foolip** [comment]
Ah, good, I can fix that.

**Comment by annevk** [comment]
That does not really explain the whatwg/encoding failure though, which was before the repository move.

**Comment by annevk** [comment]
Or the other failures before the repository move.

**Comment by foolip** [comment]
Do those failures look the same in the logs? Maybe try adding --verbose to them, might not all be the same cause...

**Comment by annevk** [comment]
They all look the same more or less. You can't really use verbose since you'd have to add that to the central script.

**Comment by annevk** [comment]
Anyway, I guess we can first fix the service-worker thing and go from there.

**Comment by annevk** [comment]
So @foolip sorted this out in #73.
