### ISSUE TITLE
Split build/ into its own repository?

### ISSUE THREAD

**Issue by foolip** [whatwg/whatwg.org#71]
AFAICT there's no particular reason that https://github.com/whatwg/whatwg.org/tree/master/resources.whatwg.org/build needs to be deployed to a web server, we could curl it from https://raw.githubusercontent.com/whatwg/whatwg.org/master/resources.whatwg.org/build/deploy.sh.

Given that, should we just put it in a separate repository? whatwg-build? common-build?

@annevk @domenic

**Comment by domenic** [comment]
I think the idea was to not rely on GitHub for hosting, or at least not rely on raw.githubusercontent.com. But, I'm not sure how important that is.

**Comment by foolip** [comment]
Hmm, so the deploy script itself relies on https://api.github.com/repos/whatwg/whatwg.org/contents/resources.whatwg.org/standard-service-worker.js being available, so it's already somewhat entangled.

But if gratuitous entanglement is worth avoiding, just leaving this alone would be OK. Finding the script is not super easy now, but I guess the script could point to where it is on GitHub?

**Comment by annevk** [comment]
I think it's fine to rely on GitHub for hosting for content that's not viewed by end users. I.e., stuff we could move elsewhere without disruption.

**Comment by foolip** [comment]
So, I can do this if you think it makes sense. Bikeshed on the name?

**Comment by annevk** [comment]
common-build seems fine, given html-build precedent.

**Comment by foolip** [comment]
I've created https://github.com/whatwg/common-build with a linear history that matches exactly what's at the tip of this repo now. Can you review it?

**Comment by annevk** [comment]
Looks good.

**Comment by foolip** [comment]
OK, so I've cloned all whatwg repos and grepped around, this is the remaining work:
- Update references to https://resources.whatwg.org/build/deploy.sh in:
  - [ ] common-build (in README.md)
  - [ ] compat
  - [ ] dom
  - [ ] infra
  - [ ] fetch
  - [ ] fullscreen
  - [ ] misc-server
  - [ ] mimesniff
  - [ ] notifications
  - [ ] quirks
  - [ ] storage
  - [ ] whatwg.org
  - [ ] xhr
- Remove resources.whatwg.org/build from the whatwg.org repo

**Comment by foolip** [comment]
OK, I've done about half of what needs to be done. Will stop here to see if there's some serious flaw before doing the second half.

**Comment by foolip** [comment]
> I think the idea was to not rely on GitHub for hosting, or at least not rely on raw.githubusercontent.com. But, I'm not sure how important that is.

Having gotten a fair bit on the way with these changes, I'm coming around to the wisdom of this. The rate limiting I ran into in https://github.com/whatwg/common-build/issues/2 was for api.github.com, but raw.githubusercontent.com might also be rate limited. I found https://github.com/Microsoft/vscode/issues/3708 suggesting that others have had trouble with this.

So... I'm leaning towards abandoning all of these changes and instead:
- Document in the common deploy.sh where its source is.
- Move over https://github.com/whatwg/common-build/issues/2 and its fix to the whatwg.org repo, then and delete the common-build repo.

Any other considerations?

**Comment by annevk** [comment]
Sounds good. Thanks a lot for finding the source!

**Comment by foolip** [comment]
I've moved over the issue/PR and made https://github.com/whatwg/common-build private, should delete it before closing this issue.

**Comment by foolip** [comment]
OK, all PRs closed, but opened new PRs for some of the drive-bys I had done. Deleting common-build and closing this issue.
