### ISSUE TITLE
Use file extensions, at least for non-HTML files

### ISSUE THREAD

**Issue by domenic** [whatwg/whatwg.org#8]
Omitting file extensions makes sense for URLs that you paste around, I think. But for image URLs and stylesheet URLs and such, it seems better to actually use the file extensions. Then you can view them using GitHub more easily.

**Comment by foolip** [comment]
I guess we could also trim some htaccess files this way.

**Comment by annevk** [comment]
We could add extensions elsewhere too to make local viewing less cumbersome and use .htaccess to rewrite the URLs.

**Comment by domenic** [comment]
Part of the solution here might be [Alias directives](https://httpd.apache.org/docs/2.4/mod/mod_alias.html) in .htaccess, which map URLs to filesystem files. So we could alias the extension-less URLs to the extension-ful files. That seems a bit strange though if we want to have a single canonical URL though, as then you could still access both the extension-less URL and the extension-ful one, I think.

**Comment by annevk** [comment]
Note that we need to preserve the URLs even of the stylesheets and images, as they are linked from legacy documents. So overall we could maybe do this for new resources, but it's not something I'm super interested in taking on for all the existing resources.

**Comment by annevk** [comment]
I think the consensus here is that we do this for new things, but refactoring old stuff is too involved.
