### ISSUE TITLE
Remove references to developers.whatwg.org for now

### ISSUE THREAD

**Issue by domenic** [whatwg/whatwg.org#9]
We should still work on getting the developers spec back and running, but until we do, we should not link to it.

**Comment by annevk** [comment]
The main problem with changing the homepage is keeping the same number of blocks. Or coming up with a new design.

**Comment by sideshowbarker** [comment]
> The main problem with changing the homepage is keeping the same number of blocks. Or coming up with a new design.

We could replace the developers.whatwg.org block with a “WHATWG GitHub’ block that links to https://github.com/whatwg

**Comment by annevk** [comment]
That's pretty good. We need to figure out what to change "Join" and "Help" into as well, but I suppose we can do it in baby steps.

**Comment by annevk** [comment]
I couldn't figure out a good text for GitHub that didn't drastically conflict with the mailing list, which needs to go, but then we run into the blocks problem.
