### ISSUE TITLE
PNG logos have the wrong color in macOS Chrome/Safari

### ISSUE THREAD

**Issue by annevk** [whatwg/whatwg.org#96]
See https://github.com/whatwg/whatwg.org/pull/95#issuecomment-332226057. Per https://webkit.org/blog/6682/improving-color-on-the-web/ the problem might be that the images have a color profile? It seems without sRGB would be assumed, which would presumably do the right thing?

**Comment by annevk** [comment]
I found http://cameratico.com/guides/web-browser-color-management-guide/ but I'm not really any wiser.

Basically, given `data:text/html,<body style=background:%233c790a>` Chrome/Safari end up with a different green than Firefox on macOS (new iMac).

According to an app Digital Color Meter, Firefox is correct...

**Comment by janbrasna** [comment]
@annevk How do #449 colors look for you? Any difference before–after?
